# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: demo 
spec:
  replicas: 5 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: demo 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: mylandmark/spring-boot-mongo:latest # Replace with the actual image tag
          name: kubernetes
          resources: {}
    status: {}
          